### PR TITLE
JENKINS-60976 - Make the `home` field optional when defining tools via Configuration-as-Code

### PR DESCRIPTION
**Pull request by mlasevich**
As per suggestion by @timja  - fix for [JENKINS-60976 ](https://issues.jenkins-ci.org/browse/JENKINS-60976 ) to make this plugin work with JCasC

### CODE REVIEW

**Comment by mlasevich** [comment]
At least if it is merged in, I will have less of a trouble using a custom build. But it would be nice it it was released.

**Comment by mlasevich** [comment]
:-( There is no "sad" reaction.

**Comment by timja** [comment]
> :-( There is no "sad" reaction.

@mlasevich or anyone else if you want to 'adopt' the plugin you just need to send the mailing list an email https://jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/

and since it's up for adoption access it'll be done quite quickly

**Comment by oleg-nenashev** [comment]
Yup. I intend to eventually come back and get some fixes over the line, but unfortunately my backlog only grows these months

**Comment by mlasevich** [comment]
I am tempted, but I really don't feel like I have sufficient knowledge of Jenkins insides yet to take that on...(I did write my first plugin over the weekend I intend to make public - but that just revealed how little I knew)

**Comment by jetersen** [comment]
@mlasevich I'd say it's a question about just jumping in and getting the knowledge 😄 Speaking as a maintainer on a few plugins you use as far as I know 😆

**Comment by timja** [comment]
Jcasc supports the checkfornull annotation to mark optional fields in a constructor,

The home field is a hidden field set in the UI only IIRC, and not actually needed.

According to the JIRA post the work around is to set home to an empty string, this allows omitting that

**Comment by oleg-nenashev** [comment]
I will cut the release

**Pull request merged**
