### PR TITLE
[JENKINS-54154] - Fix configuration-as-code support

### PR DESCRIPTION
**Pull request by ndeloof**

### CODE REVIEW

**Comment by ndeloof** [comment]
> API-breaking change 

really ? On couldn't have used this constructor with a List of anything but ToolProperty, so I assume there's no actual breaking change.

**Comment by ansig** [comment]
Any chance of seeing this merged and released soon if it is not a breaking change? https://github.com/jenkinsci/configuration-as-code-plugin/issues/97 is a blocker for me.

**Comment by oleg-nenashev** [comment]
> really ? On couldn't have used this constructor with a List of anything but ToolProperty, so I assume there's no actual breaking change.

You are right, it's not according to the specs

**Comment by oleg-nenashev** [comment]
There was no JIRA for it, so I just missed it. 
https://issues.jenkins-ci.org/browse/JENKINS-54154 has been created

**Pull request merged**
